name: Update i18n files

on:
  push:
    paths:
    - 'src/data/reference/*.json'
    - 'src/data/*.yml'

jobs:
  build:
    name: Update i18n files
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
      - name: Install Node.JS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm install
      - name: Update json files
        run: |
          npm run grunt update-json-i18n-files
      - name: Update yaml files
        run: |
          npm run grunt update-yaml-i18n-files
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: 'Automatic update of translation files (${{ github.sha }})'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 